/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package irrgarten.UI;

import irrgarten.Directions;
import irrgarten.GameState;

/**
 *
 * @author javie
 */
public class GraphicsUI extends javax.swing.JFrame implements UI{
    private Cursors cursors;
    
    /**
     * Creates new form GraphicsUI
     */
    public GraphicsUI() {
        initComponents();
        this.setSize(800,800);
        this.setVisible(true);
        cursors = new Cursors(this, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LabyrinthText = new javax.swing.JTextArea();
        LabyrinthLabel = new javax.swing.JLabel();
        PlayerLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CurrentPlayerText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        PlayerText = new javax.swing.JTextArea();
        WinnerLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        WinnerText = new javax.swing.JTextArea();
        MonsterLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        MonsterText = new javax.swing.JTextArea();
        LogLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        LogText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LabyrinthText.setColumns(20);
        LabyrinthText.setRows(5);
        jScrollPane1.setViewportView(LabyrinthText);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 80, 270, 210);

        LabyrinthLabel.setText("Labyrinth");
        getContentPane().add(LabyrinthLabel);
        LabyrinthLabel.setBounds(310, 170, 80, 30);

        PlayerLabel.setText("Player");
        getContentPane().add(PlayerLabel);
        PlayerLabel.setBounds(20, 220, 60, 30);

        CurrentPlayerText.setColumns(20);
        CurrentPlayerText.setRows(5);
        jScrollPane2.setViewportView(CurrentPlayerText);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(100, 100, 190, 70);

        jLabel1.setText("CurrentPlayer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 130, 80, 16);

        PlayerText.setColumns(20);
        PlayerText.setRows(5);
        jScrollPane3.setViewportView(PlayerText);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(100, 200, 190, 80);

        WinnerLabel.setText("Winner");
        getContentPane().add(WinnerLabel);
        WinnerLabel.setBounds(30, 50, 50, 16);

        WinnerText.setColumns(20);
        WinnerText.setRows(5);
        jScrollPane4.setViewportView(WinnerText);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(100, 20, 190, 60);

        MonsterLabel.setText("Monster");
        getContentPane().add(MonsterLabel);
        MonsterLabel.setBounds(30, 330, 60, 30);

        MonsterText.setColumns(20);
        MonsterText.setRows(5);
        jScrollPane5.setViewportView(MonsterText);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(100, 300, 190, 80);

        LogLabel.setText("Log");
        getContentPane().add(LogLabel);
        LogLabel.setBounds(20, 486, 60, 40);

        LogText.setColumns(20);
        LogText.setRows(5);
        jScrollPane6.setViewportView(LogText);

        getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(100, 400, 340, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
    public Directions nextMove() {
        return cursors.getDirection();
    }

    @Override
    public void showGame(GameState gameState) {
        CurrentPlayerText.setText(Integer.toString(gameState.getCurrentPlayer()));
        LabyrinthText.setText(gameState.getLabyrinthv());
        LogText.setText(gameState.getLog());
        MonsterText.setText(gameState.getMonsters());
        PlayerText.setText(gameState.getPlayers());
        if(gameState.getWinner()){
            WinnerText.setText("Player " + gameState.getCurrentPlayer());
        }
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CurrentPlayerText;
    private javax.swing.JLabel LabyrinthLabel;
    private javax.swing.JTextArea LabyrinthText;
    private javax.swing.JLabel LogLabel;
    private javax.swing.JTextArea LogText;
    private javax.swing.JLabel MonsterLabel;
    private javax.swing.JTextArea MonsterText;
    private javax.swing.JLabel PlayerLabel;
    private javax.swing.JTextArea PlayerText;
    private javax.swing.JLabel WinnerLabel;
    private javax.swing.JTextArea WinnerText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
